#include"energytrading.h"
//display list of seller
void display_list_of_trans_seller(SellerBTreeNode* root) {
    if (root != NULL) {
        for (int i = 0; i < root->num_keys; i++) {
            display_list_of_trans_seller(root->children[i]);//all the left child
            printf("\n Seller ID: %s | Price/kWh <300($): %.2f | Price/kwH>=300($): %.2f)|Total Revenue:$%f\n",
                   root->keys[i]->seller_id, root->keys[i]->price_kwh_lt_300, root->keys[i]->price_kwh_gt_300,root->keys[i]->total_revenue);
            printf("Transaction:\n");
            printTableHeader();
            traverse(root->keys[i]->Transaction_Subtree);
        }
        display_list_of_trans_seller(root->children[root->num_keys]);//traverse right child
    }
}
// Create and display set of Transactions for Every Seller
void displayAllSellersWithBuyers(SellerBTreeNode* root) {
    if (root == NULL) return;

    for (int i = 0; i < root->num_keys; i++) {
        displayAllSellersWithBuyers(root->children[i]); 
        displayRegularBuyers(root->keys[i]); 
    }
    displayAllSellersWithBuyers(root->children[root->num_keys]); 
}
//display regular buyer
void displayRegularBuyers(seller_node* seller) {
    if (seller == NULL || seller->regularBuyers == NULL) {
        return;  // Skip if seller doesn't exist or has no regular buyers
    }

    printf("\nSeller: %s\n", seller->seller_id);
    printf("Regular Buyers:\n");
    printf("-------------\n");
    
    regularBuyer* current = seller->regularBuyers;
    while (current != NULL) {
        printf("- %s\n", current->buyer_id);
        current = current->next;
    }
    printf("-------------\n");
}
//Calculate Total Revenue by Seller
void total_revenue_particular_seller(SellerBTreeNode**root,char *sellerID)
{
    seller_node* seller = searchSeller(*root, sellerID);
    if (seller)
    {
        printf("\nTotal Revenue generated by selled %s is $%f\n",seller->seller_id,seller->total_revenue);
    }
    else 
    {
         printf("\nSeller ID %s does not exist!!\n",sellerID);
    }
}